minor fix yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,32 +26,32 @@ jobs:
    steps:
     - checkout
     - run:
-          name: Install dependencies
-          command: |
-            sudo apt update
-            sudo apt install -y awscli docker
-      - run:
-          name: Setup AWS assume role
-          command: |
-            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
-              < <(aws sts assume-role-with-web-identity \
-                  --role-arn "${AWS_ROLE_ARN}" \
-                  --role-session-name "${AWS_ROLE_SESSION_NAME}" \
-                  --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
-                  "$@" \
-                  --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
-                  --output text)
-            if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
-                echo "Failed to assume role"
-                exit 1
-            else
-                {
-                    echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
-                    echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
-                    echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
-                } >>"$BASH_ENV"
-                echo "Assume role with web identity succeeded"
-            fi
+        name: Install dependencies
+        command: |
+          sudo apt update
+          sudo apt install -y awscli docker
+    - run:
+        name: Setup AWS assume role
+        command: |
+          read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
+            < <(aws sts assume-role-with-web-identity \
+                --role-arn "${AWS_ROLE_ARN}" \
+                --role-session-name "${AWS_ROLE_SESSION_NAME}" \
+                --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
+                "$@" \
+                --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
+                --output text)
+          if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
+              echo "Failed to assume role"
+              exit 1
+          else
+              {
+                  echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
+                  echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
+                  echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
+              } >>"$BASH_ENV"
+              echo "Assume role with web identity succeeded"
+          fi
     - run:
         name: Hadolint run
         command: |
